version: "3.7"

services:
  gateway:
    build:
      context: gateway/docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./gateway:/app
    depends_on:
      - frontend-node
      - api

#  frontend:
#    build:
#      context: frontend/docker
#      dockerfile: development/nginx/Dockerfile
#    volumes:
#      - ./frontend:/app
#    depends_on:
#      - frontend-node

  frontend-node:
    build:
      context: frontend/docker/development/node
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev
    tty: true
    restart: always

  frontend-node-cli:
    build:
      context: frontend/docker/development/node
    volumes:
      - ./frontend:/app

  api:
    build:
      context: backend/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: backend/docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./backend:/app
    environment:
      PHP_IDE_CONFIG: serverName=API
    depends_on:
     - api-mariadb
     - mailhog

  api-php-cli:
    build:
      context: backend/docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./backend:/app
    environment:
      PHP_IDE_CONFIG: serverName=API
    depends_on:
      - api-mariadb
      - mailhog
  api-mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: dbpass
      MARIADB_DATABASE: wonderland
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  database:
