version: "3.7"

services:
  gateway:
    build:
      context: gateway/docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "6001:6001"
    volumes:
      - ./gateway:/app
    depends_on:
      - frontend-node
      - api

#  frontend:
#    build:
#      context: frontend/docker
#      dockerfile: development/nginx/Dockerfile
#    volumes:
#      - ./frontend:/app
#    depends_on:
#      - frontend-node

  frontend-node:
    build:
      context: frontend/docker/development/node
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev
    tty: true
    restart: always

  frontend-node-cli:
    build:
      context: frontend/docker/development/node
    volumes:
      - ./frontend:/app

  api:
    build:
      context: backend/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: backend/docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./backend:/app
    environment:
      PHP_IDE_CONFIG: serverName=API
    depends_on:
     - api-mariadb
     - mailhog

  api-php-cli:
    build:
      context: backend/docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./backend:/app
    environment:
      PHP_IDE_CONFIG: serverName=API
    depends_on:
      - api-mariadb
      - mailhog
  api-horizon:
    build:
      context: backend/docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - api-mariadb
      - mailhog
    entrypoint: ['php', 'artisan', 'horizon']
  api-mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: dbpass
      MARIADB_DATABASE: wonderland
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    command:
      - redis-server
      - --appendonly yes
#      - --requirepass $$REDISCLI_AUTH
#    environment:
#      REDISCLI_AUTH: secret@123
    restart: unless-stopped
    volumes:
      - redis-vol:/data
    ports:
      - "6379:6379"

  laravel-echo-server:
    image: oanhnn/laravel-echo-server:latest
    depends_on:
      - redis
    environment:
      LARAVEL_ECHO_SERVER_AUTH_HOST: "http://api:8081"
      LARAVEL_ECHO_SERVER_AUTH_PORT: 8081
      LARAVEL_ECHO_SERVER_DEBUG: 'true'
      LARAVEL_ECHO_SERVER_DB: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PREFIX: laravel_
#      REDIS_PASSWORD: secret@123
      REDIS_DB: 0
    ports:
      - "8001:6001"
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  database:
  redis-vol:
