version: "3.7"

services:
  gateway:
    build:
      context: gateway/docker
      dockerfile: development/nginx/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: frontend/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./frontend:/app

  api:
    build:
      context: backend/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - api-php-fpm
      - api-mariadb

  api-php-fpm:
    build:
      context: backend/docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./backend:/app
    environment:
      DEBUG: 1
      APP_ENV: local
      PHP_IDE_CONFIG: serverName=API
  api-php-cli:
    build:
      context: backend/docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./backend:/app
    environment:
      DEBUG: 1
      APP_ENV: dev
  api-mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: dbpass
      MARIADB_DATABASE: wonderland
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  database:
