site:
	ansible-playbook -i hosts.yml site.yml -vvv

renew-certificates:
	ansible-playbook -i hosts.yml renew-certificates.yml

authorize:
	ansible-playbook -i hosts.yml authorization.yml

docker-login:
	ansible-playbook -i hosts.yml docker-login.yml -vvv

